using System;

namespace Tonberry.Core;

internal static class Resources
{
    public const StringComparison StrCompare = StringComparison.OrdinalIgnoreCase;

    public const string Breaking = "BREAKING CHANGE: ";

    public const string ChangelogFile = "CHANGELOG.md";

    public const string ChangelogHeader = "All commits to this project are documented in this file by [tonberry](https://github.com/ashscodes/tonberry)! Please do not edit this file or remove this header.";

    public const string CommitCloses = "closes #{0}";

    public const string CommitPreview = "[Preview] {0} [{1}:{2}] '{3}'";

    public const string CommitResolves = "resolves {0}";

    public const string DefaultTag = "v{0}";

    public const string DefaultMonoRepoProjectTag = "v{0}/#/{1}";

    public const string InvalidCommitMessage = "A new commit message requires a type and short message describing the changes. Please specify a value for 'commitMessage' and 'type'.";

    public const string InvalidEnumType = "The value provided '{0}' is not valid. The following values are available: {1}.";

    public const string MarkdownBreakingChangeHeader = ":warning: BREAKING CHANGES";

    public const string MarkdownBreaking = "> * **{0}**: {1} ({2})";

    public const string MarkdownBreakingNoScope = "> * {0} ({1})";

    public const string MarkdownCommit = "* **{0}**: {1} ({2})";

    public const string MarkdownCommitNoScope = "* {0} ({1})";

    public const string MarkdownContributorCommit = "* {0} - ({1})";

    public const string MarkdownContributorEmoji = ":clap:";

    public const string MarkdownContributorThanks = "This release was contributed to by the following amazing people. A huge thank to all of you!";

    public const string MarkdownContributorTitle = "Contributors";

    public const string MarkdownHeader = "{0} {1}{2}";

    public const string MarkdownLink = "[{0}]({1})";

    public const string MarkdownReleaseHeader = "{0} {1}{2} ({3})";

    public const string MonoRepoPathExample = "src/path/to/project/folder";

    public const string NoCommitsFound = "The current branch '[{0}] {1}' has no new commits. Please make a new commit or pull any new changes.";

    public const string NoProjectDefined = "The project '{0}' was not specified as a monorepo in the root configuration.";

    public const string NoProjectsDefined = "No individual projects were specified for the monorepo in the root configuration.";

    public const string NoRepositoryFound = "The path defined, '{0}', contained no git repository.";

    public const string NoStagedFiles = "The specified git repository has no staged files. If you intended to stage all files, please specify 'true' for the parameter \"stageAll\".";

    public const string ProjectChangelogFile = "CHANGELOG_{0}.md";

    public const string ReleaseMessage = "chore: Release of version {0}.";

    public const string RootConfigNotFound = "The root tonberry config file could not be found in the current/specified directory or was unreadable. You can generate a new config with 'tonberry init'.";

    public const string ShaConfigMessage = "Auto-Generated: Please do not edit value.";

    public const string StringIsNullOrEmpty = "The value for '{0}' is required, but was null or empty.";

    public const string TonberryRootConfig = "tonberry.config.yml";

    public const string UnexpectedType = "Could not process the object of type '{0}'. The expected type is '{1}'.";

    public const string VersionMarkdownRow = "| {0} | {1} |";
}